name: generate pacman game

on:
  schedule:
  - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          
      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Push to output branch
        run: |
          mkdir -p temp_output
          cd temp_output
          
          git init
          git remote add origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin output || git checkout --orphan output
          git checkout output || git checkout --orphan output
          
          cp -r ../dist/* .
          
          git add .
          git commit -m "Generate pacman animation" || echo "No changes to commit"
          git push -u origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}